### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by valosekj** [sct-pipeline/normative-metrics#1]
Update info regarding download of data (migration from openneruro to github - https://github.com/sct-pipeline/spine-generic/issues/98)

**Comment by morrme** [comment]
Has multi-subject been moved as well? There seems to only be a new location identified for single subject.

**Comment by valosekj** [comment]
You are right. I think only single-subject dataset has been moved yet. Migration of multi-subject dataset is planned (see to-do in https://github.com/sct-pipeline/spine-generic/issues/98)

**Comment by morrme** [comment]
That's what I figured. So this task cannot be completed until that migration is complete, correct?

**Comment by valosekj** [comment]
Exactly. I created this as a reminder for me to update README when migration will be done.

**Comment by valosekj** [comment]
Need to be updated:

- [x] spine generic version in _Prerequisites_
- [x] dataset download command
- [x] switch from `-task` to `-script` flag in `sct_run_batch.py` how was changed [here ](https://github.com/neuropoly/spinalcordtoolbox/pull/2795/commits/44ec417db04392ca6b847af004da9e85c9864535)

**Comment by valosekj** [comment]
Fixed in https://github.com/sct-pipeline/normative-metrics/commit/d9411b2228e3d4cff3a2fad1d3c15114a2bdbfda
