### ISSUE TITLE
Changes of script for generating figures

### ISSUE THREAD

**Issue by valosekj** [sct-pipeline/normative-metrics#4]
- [ ] Rename https://github.com/sct-pipeline/normative-metrics/blob/master/scripts/generate_figures.py to do not have same name as https://github.com/spine-generic/spine-generic/blob/master/spinegeneric/cli/generate_figure.py, it could be confusing.
- [x] Implement exclusion of subjects using input yml config file, similar like [here](https://github.com/spine-generic/spine-generic/pull/168)

**Comment by jcohenadad** [comment]
> Rename https://github.com/sct-pipeline/normative-metrics/blob/master/scripts/generate_figures.py to do not have same name as https://github.com/spine-generic/spine-generic/blob/master/spinegeneric/cli/generate_figure.py, it could be confusing.

note that the entry point for the CLI call from the terminal is already `sg_generate_figures` (specifically to prevent confusion)

**Comment by valosekj** [comment]
I am closing this issue, because, there is planned merging of `normative-metrics/generate_figures.py` with the original `spine-generic/generate_figures.py` script, details here - https://github.com/sct-pipeline/normative-metrics/pull/5#issuecomment-681506795
